### ISSUE TITLE
Crashes after launch

### ISSUE THREAD

**Issue by brodycritchlow** [TDToolbox/BTD6-Mod-Manager#2]
When I open the program everything looks fine, then I go to click on yes for the tutorial. And right before I do it crashes the application. Also, sometimes when i get to the prompt I cant click on yes. Is there any fix for this? I'm using the latest version.

**Comment by gurrenm3** [comment]
This issue has been fixed

**Comment by brodycritchlow** [comment]
It hasn't been fixed it doesn't work still

**Comment by gurrenm3** [comment]
Are you using the latest version of BTD6 Mod Manager? Version 2.1.1?
Also, make sure you have the latest version of .Net Framework: https://dotnet.microsoft.com/download/dotnet-framework/net48
